#!/usr/bin/env python3
"""Sync index_en.html from index.html (structure parity, EN copy)."""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
de = (ROOT / "index.html").read_text(encoding="utf-8")
en = de.replace('lang="de"', 'lang="en"', 1)

pairs = [
    ("Wo Ihr Hotel Umsatz verliert | PMS-/OTA-Prüfung &amp; IT Support | BIT Zürich",
     "Where your hotel loses revenue | PMS/OTA review &amp; IT Support | BIT Zurich"),
    ("BIT prüft PMS- und OTA-Daten, Gebühren, Folios und operative Systemfälle für Hotels. Zusätzlich KMU IT, Microsoft 365, Websites und Kalender.",
     "BIT reviews PMS and OTA data, fees, folios and operational system cases for hotels. Additionally SME IT, Microsoft 365, websites and calendars."),
    ("PMS OTA Prüfung, Hotel Revenue Control, Hotel IT Support Schweiz, SIHOT.PMS Anwenderunterstützung, Folio Billing Review, KMU IT Zürich, Microsoft 365 Support",
     "PMS OTA review, hotel revenue control, hotel IT support Switzerland, SIHOT.PMS user support, folio billing review, SME IT Zurich, Microsoft 365 support"),
    ('<meta property="og:url" content="https://boksitsupport.ch">',
     '<meta property="og:url" content="https://boksitsupport.ch/index_en.html">'),
    ('<link rel="canonical" href="https://boksitsupport.ch/">',
     '<link rel="canonical" href="https://boksitsupport.ch/index_en.html">'),
    ('<link rel="alternate" hreflang="en" href="https://boksitsupport.ch/index_en.html">',
     '<link rel="alternate" hreflang="en" href="https://boksitsupport.ch/index_en.html">\n    <link rel="alternate" hreflang="x-default" href="https://boksitsupport.ch/">'),
    ("PMS-/OTA-Prüfung, Gebühren, Folios und operative Systemfälle für Hotels; KMU IT, Microsoft 365, Websites und Kalender – BIT Zürich.",
     "PMS/OTA review, fees, folios and operational system cases for hotels; SME IT, Microsoft 365, websites and calendars - BIT Zurich."),
    ('"addressLocality": "Zürich"', '"addressLocality": "Zurich"'),
    ('href="index.html#', 'href="index_en.html#'),
    ('href="index.html"', 'href="index_en.html"'),
    ('href="services.html"', 'href="services-en.html"'),
    ('href="it-matrix.html"', 'href="it-matrix-en.html"'),
    ('href="kontakt.html"', 'href="kontakt-en.html"'),
    ('href="legal.html"', 'href="legal-en.html"'),
    ("PMS-/Hotel-Systeme", "PMS / Hotel Systems"),
    ("Leistungen", "Services"),
    ("Kontakt", "Contact"),
    ("Hauptnavigation", "Main navigation"),
    ("Sprache wählen", "Choose language"),
    ("Menü öffnen", "Open menu"),
    ("Mobile Navigation", "Mobile navigation"),
    ("Wo Ihr Hotel Umsatz verliert.", "Where your hotel loses revenue."),
    ("Prüfung von PMS- und OTA-Daten, Gebühren, Folios und operativen Systemfällen.",
     "Review of PMS and OTA data, fees, folios and operational system cases."),
    ("Prüfung anfragen", "Request a review"),
    ("Leistungen ansehen", "View services"),
    ("Unabhängig. Klar abgegrenzt. Remote oder vor Ort nach Absprache.",
     "Independent. Clear scope. Remote or on-site by arrangement."),
    ("Kleine Abweichungen werden in der Hotellerie teuer.",
     "Small deviations become expensive in hospitality processes."),
    ("Reservierungen, Folios, Gebühren und Buchungskanäle greifen täglich ineinander. BIT prüft klar abgegrenzte Abweichungen auf Basis bereitgestellter oder neutral aufbereiteter Unterlagen.",
     "Reservations, folios, fees and booking channels interlock daily. BIT reviews clearly scoped deviations based on materials supplied by clients or prepared independently."),
    ('aria-label="Ergebnisziele"', 'aria-label="Outcome goals"'),
    ("Abweichungen finden", "Find deviations"),
    ("Ursache einordnen", "Classify the cause"),
    ("Nächsten Schritt festlegen", "Define the next step"),
    ("Prüffelder", "Review areas"),
    ("BIT prüft klar abgegrenzte Bereiche, in denen operative Fehler Zeit, Geld oder Kontrolle kosten.",
     "BIT reviews clearly defined areas where operational errors cost time, money or control."),
    ("Alle Leistungen ansehen", "View all services"),
    ("PMS-/OTA-Abgleich", "PMS/OTA reconciliation"),
    ("Abgleich von Buchungen, Raten, Kategorien, Folios und OTA-Daten.",
     "Reconciliation of bookings, rates, categories, folios and OTA data."),
    ("PMS-/OTA-Reconciliation", "PMS/OTA reconciliation"),
    ("Folio &amp; Billing Review", "Folio &amp; billing review"),
    ("Rate &amp; Mapping Review", "Rate &amp; mapping review"),
    ("Stammdatenqualität", "Master data quality"),
    ("Gebühren &amp; Revenue Control", "Fees &amp; revenue control"),
    ("Prüfung von No-Shows, Stornos, Add-ons, Kurtaxe und abrechnungsrelevanten Fällen.",
     "Review of no-shows, cancellations, add-ons, tourist tax and billing-relevant cases."),
    ("Abrechnungsabweichungen prüfen", "Billing discrepancy review"),
    ("Erfahrung mit SIHOT.PMS aus praktischer Anwendung. Keine Herstellervertretung und kein offizieller Hersteller-Support.",
     "Experience with SIHOT.PMS from practical use. No vendor representation and no official vendor support."),
    ("KMU IT &amp; Web", "SME IT &amp; web"),
    ("Klar abgegrenzter Support für Microsoft 365, Windows 11, Websites, Kalender und einfache Automationen.",
     "Clearly scoped support for Microsoft 365, Windows 11, websites, calendars and simple automations."),
    ("Kalender-/Buchungslösungen", "calendar/booking solutions"),
    ("Kalendern", "calendars"),
    ("Kalender", "calendars"),
    ("Vorgehen", "Process"),
    ('aria-label="Vorgehensschritte"', 'aria-label="Process steps"'),
    ("Anfrage", "Request"),
    ("Kurzer Beschrieb per E-Mail.", "Brief description by email."),
    ("Einschätzung", "Assessment"),
    ("BIT prüft, ob der Fall sinnvoll eingegrenzt werden kann.",
     "BIT checks whether the case can be scoped sensibly."),
    ("Prüfung", "Review"),
    ("Kleine Erstprüfung oder Fixpreis nach Umfang.",
     "Small initial review or fixed price by scope."),
    ("Ergebnis", "Outcome"),
    ("Befund, Ursache und empfohlener nächster Schritt.",
     "Findings, cause and recommended next step."),
    ("Über BIT", "About BIT"),
    ('alt="Stefan Bogdanovic - BIT Boks IT Support Zürich"',
     'alt="Stefan Bogdanovic - BIT Boks IT Support Zurich"'),
    ("BIT - Boks IT Support wird von Stefan Bogdanovic in Zürich betrieben. Der Fokus liegt auf praxisnaher Unterstützung bei Hotel-Systemprozessen, PMS-/OTA-nahen Abläufen, KMU-IT und strukturierter Prozessdokumentation.",
     "BIT - Boks IT Support is operated by Stefan Bogdanovic in Zurich. The focus is on practical support with hotel system processes, PMS/OTA-related workflows, SME IT and structured process documentation."),
    ("Je nach Auftrag arbeitet BIT projektbezogen mit ausgewählten Freelancern, Fachpersonen oder kleinen Umsetzungsteams zusammen. Die Verantwortung, Koordination und Qualitätssicherung bleiben dabei klar bei BIT.",
     "Depending on the engagement, BIT works on a project basis with selected freelancers, specialists or small implementation teams. Responsibility, coordination and quality assurance remain clearly with BIT."),
    ("Die Arbeit erfolgt unabhängig, klar abgegrenzt und ohne Verwendung vertraulicher Informationen aktueller oder früherer Arbeitgeber.",
     "The work is independent, clearly scoped and does not use confidential information from current or former employers."),
    ("Direkt Kontakt aufnehmen", "Contact directly"),
    ("Direkt Contact aufnehmen", "Contact directly"),
    ("Ein Fall genügt für den ersten Schritt.", "One case is enough for the first step."),
    ("Senden Sie einen kurzen Beschrieb. BIT gibt eine Einschätzung, ob eine Prüfung sinnvoll ist.",
     "Send a brief description. BIT will assess whether a review makes sense."),
    ("E-Mail senden", "Send email"),
    ("Häufig gestellte Fragen", "Frequently asked questions"),
    ("Arbeiten Sie nur mit Hotels?", "Do you work only with hotels?"),
    ("Nein. Schwerpunkt sind Hotels und PMS-/OTA-Prozesse. Zusätzlich unterstützt BIT KMU bei IT, Websites und Kalendern.",
     "No. The focus is hotels and PMS/OTA processes. BIT also supports SMEs with IT, websites and calendars."),
    ("Was ist der Unterschied zu klassischem IT-Support?", "How is this different from standard IT support?"),
    ("BIT betrachtet nicht nur Technik, sondern auch operative Abläufe: Buchungen, Folios, Gebühren, Datenqualität und Prozessfehler.",
     "BIT considers not only technology but also operational processes: bookings, folios, fees, data quality and process errors."),
    ("Brauchen Sie direkten Systemzugriff?", "Do you need direct system access?"),
    ("Oft nicht. Screenshots, Exporte oder Fallbeschreibungen reichen für den Start. Zugriff nur nach Absprache.",
     "Often not. Screenshots, exports or case descriptions are enough to start. Access only by agreement."),
    ("Gibt es langfristige Bindung?", "Is there a long-term commitment?"),
    ("Nein. Kleine, klar abgegrenzte Einsätze sind möglich.", "No. Small, clearly scoped engagements are possible."),
    ("Bieten Sie auch Websites und Kalender an?", "Do you also offer websites and calendars?"),
    ("Ja. BIT unterstützt einfache Websites, Landingpages, direkte Kontaktseiten und Kalender-/Buchungslösungen.",
     "Yes. BIT supports simple websites, landing pages, direct contact pages and calendar/booking solutions."),
    ("Ist BIT Anbieter oder Herstellervertretung für PMS?", "Is BIT a PMS provider or manufacturer representative?"),
    ("Nein. BIT bietet unabhängige Anwender- und Prozessunterstützung auf Basis praktischer Hotel-Erfahrung.",
     "No. BIT provides independent user and process support based on practical hotel experience."),
    ("Zürich, Schweiz", "Zurich, Switzerland"),
    ("Impressum", "Legal notice"),
    ("Datenschutz", "Privacy"),
    ('<a href="index_en.html" class="lang-link" lang="en">EN</a>',
     '<a href="index_en.html" class="lang-link active" lang="en" aria-current="page">EN</a>'),
    ('<a href="index_en.html" class="lang-link active" lang="de" aria-current="page">DE</a>',
     '<a href="index.html" class="lang-link" lang="de">DE</a>'),
]

for old, new in pairs:
    en = en.replace(old, new)

favicon = """    <link rel="icon" type="image/png" sizes="32x32" href="favicon.png">
    <link rel="apple-touch-icon" sizes="180x180" href="favicon.png">
    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
"""
if "favicon.png" not in en:
    en = en.replace(
        '<meta name="viewport" content="width=device-width, initial-scale=1.0">',
        '<meta name="viewport" content="width=device-width, initial-scale=1.0">\n' + favicon,
        1,
    )

en = en.replace('loading="lazy">', 'loading="lazy" decoding="async">', 1)

(ROOT / "index_en.html").write_text(en, encoding="utf-8", newline="\n")
print("Wrote index_en.html", len(en), "bytes")
